"""
Configuration Constants for BanditGPT

This package contains all configuration constants, parameters, and immutable data
files (model registries) used across the project. Centralized constant management
for better maintainability.

Data files:
    models.json       — Consolidated model registry (85+ models with pricing)
"""

from pathlib import Path

# ==============================================================================
# Model Configuration
# ==============================================================================

# SentenceTransformer model used for semantic embeddings throughout the project.
#
# Rationale:
# - `all-MiniLM-L6-v2` is an excellent speed baseline, but it is no longer
#   state-of-the-art on embedding quality.
# - `BAAI/bge-m3` is a strong modern embedding model (multilingual + strong
#   retrieval / semantic matching), which improves routing signal quality.
#
# IMPORTANT: The shipped PCA artifact (`pca_32.joblib`) is trained specifically
# for this encoder. If you change this default, you must regenerate PCA (and any
# warmup priors) using `bandit_gpt.calibration.train_pca()` and
# `bandit_gpt.calibration.generate_warmup_priors()`.
DEFAULT_SENTENCE_TRANSFORMER = "BAAI/bge-m3"

# Model tier mapping for capability-equivalent substitutions
# Used when a model is no longer available but has a capability-tier equivalent
STRONG_MODEL_EQUIVALENTS = ["openai/gpt-4.1", "openai/gpt-4.1"]

# ==============================================================================
# Artifact Paths
# ==============================================================================

# Package-internal paths (resolve correctly both in dev and after pip install)
_PACKAGE_DIR = Path(__file__).parent.parent
_PACKAGE_DATA_DIR = _PACKAGE_DIR / "data"
_PACKAGE_ARTIFACTS_DIR = _PACKAGE_DATA_DIR / "artifacts"

# Source-tree paths (used only by experiment scripts outside the package)
PROJECT_ROOT = Path(__file__).parent.parent.parent.parent
ARTIFACTS_DIR = PROJECT_ROOT / "src" / "artifacts"
DATA_DIR = PROJECT_ROOT / "data"

# PCA model trained on LMSYS Chatbot Arena prompts using DEFAULT_SENTENCE_TRANSFORMER.
#
# Trained on ~46K LMSYS arena prompts (strictly disjoint from dev/holdout
# experimental data).  Shipped inside the wheel so first-time users skip
# JIT retraining.
#
# 15 components capture ~21% of variance — balances routing signal
# richness with a healthy samples-per-feature ratio for both K=2 and K=10.
# The full 32-component artifact is retained for reference / ablations.
DEFAULT_PCA_PATH = _PACKAGE_ARTIFACTS_DIR / "pca_15.joblib"
FULL_PCA_PATH = _PACKAGE_ARTIFACTS_DIR / "pca_32.joblib"

# Generic PCA: trained on C4 web text (no routing connection).
# Provides unbiased baseline for routing signal analysis.
# Generate with: python3 scripts/train_pca_generic.py --n-components 32
GENERIC_PCA_PATH = ARTIFACTS_DIR / "pca_32_generic.joblib"

# Three-way split definition for all experiments.
# Based on K=10 model coverage: prompts with rewards for all 10 portfolio
# models are split into prior-train (40%), online-learn (60%), and holdout.
# This yields ~1,028 prior-train / ~1,543 online-learn / ~1,483 holdout
# prompts — substantially more data than the legacy 43-model filter.
THREE_WAY_SPLITS_PATH = ARTIFACTS_DIR / "splits_three_way.json"

# Canonical data paths — all reward data lives in data_collection/
DATA_COLLECTION_DIR = PROJECT_ROOT / "data_collection"

# Portfolio-specific warmup priors.  The K=10 artifact is the master
# (built from the 1,028-prompt LMSYS prior-train pool).  Smaller
# portfolios are extracted by filtering to the relevant model subset.
WARMUP_PRIORS_DIR = DATA_COLLECTION_DIR / "warmup_priors"
K2_WARMUP_PRIORS_PATH = WARMUP_PRIORS_DIR / "priors_warmup_k2_15comp.joblib"
K3_WARMUP_PRIORS_PATH = WARMUP_PRIORS_DIR / "priors_warmup_k3_15comp.joblib"
K5_WARMUP_PRIORS_PATH = WARMUP_PRIORS_DIR / "priors_warmup_k5_15comp.joblib"
K10_WARMUP_PRIORS_PATH = WARMUP_PRIORS_DIR / "priors_warmup_k10_15comp.joblib"
MULTIMODEL_WARMUP_PRIORS_PATH = K10_WARMUP_PRIORS_PATH
# Pre-computed embeddings cache (generated by scripts/precompute_embeddings.py).
EMBEDDINGS_CACHE_DIR = DATA_COLLECTION_DIR / "embeddings"
EMBEDDINGS_CACHE_PATH = EMBEDDINGS_CACHE_DIR / "embeddings_pca15.npz"

OFFLINE_DATASET_DIR = DATA_COLLECTION_DIR / "rewards"
PROMPTS_DIR = DATA_COLLECTION_DIR / "prompts"
CACHE_DIR = DATA_COLLECTION_DIR / "cache"
LMSYS_BATTLES_PATH = PROMPTS_DIR / "lmarena_battles_en.jsonl"
K3_MODELS_PATH = DATA_COLLECTION_DIR / "config" / "models_k3.json"
K5_MODELS_PATH = DATA_COLLECTION_DIR / "config" / "models_k5.json"
K10_MODELS_PATH = DATA_COLLECTION_DIR / "config" / "models_k10.json"

# All models datasets (44 models: original 43 + gemini-2.5-flash)
DEV_DATA_PATH_ALL_MODELS = OFFLINE_DATASET_DIR / "dev_rewards_complete_all_models.jsonl.gz"
HOLDOUT_DATA_PATH_ALL_MODELS = OFFLINE_DATASET_DIR / "holdout_rewards_complete_all_models.jsonl.gz"



# Calibrated router path
BANDIT_DATA_DIR = PROJECT_ROOT / "src" / "bandit_gpt" / "data"
CANONICAL_CALIBRATED_ROUTER_PATH = BANDIT_DATA_DIR / "artifacts" / "canonical_router_calibrated.joblib"

# Model registry path
DEFAULT_MODEL_REGISTRY_PATH = Path(__file__).parent / "models.json"
