#!/usr/bin/env python3
"""
Compare HelpSteer2 correct/incorrect labels with labels generated by Gemini 3.0 Flash.

Usage:
    python scripts/compare_helpsteer_gemini.py
"""

import os
import sys
import json
import time
import argparse
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
import pandas as pd
from tqdm import tqdm
from dotenv import load_dotenv

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

load_dotenv(PROJECT_ROOT / ".env")

from banditgpt.core.model_manager import call_openrouter

# Configuration
MODEL_ID = "google/gemini-3-flash-preview"
HELPSTEER_THRESHOLD = 2.5
OUTPUT_FILE = PROJECT_ROOT / "results" / "helpsteer_gemini_comparison.jsonl"
MAX_WORKERS = 20

def get_gemini_label(prompt, response):
    """
    Query Gemini 3.0 Flash to label the response as Correct or Incorrect.
    """
    system_prompt = (
        "You are an expert judge evaluating the correctness of an AI response.\n"
        "Determine if the response is factually correct and helpful.\n"
        "If it is correct, output 'Label: Correct'.\n"
        "If it is incorrect or contains significant errors, output 'Label: Incorrect'.\n"
        "Provide a brief explanation before the label."
    )
    
    user_content = f"Prompt: {prompt}\n\nResponse: {response}"
    full_prompt = f"{system_prompt}\n\n{user_content}"
    
    try:
        content, meta = call_openrouter(MODEL_ID, full_prompt, max_tokens=2000)
        if not content:
            return None, "No content returned"
        
        # Debug print to see raw output (optional, can be noisy)
        # print(f"DEBUG: {content[:100]}...")
        
        # Parse label (case-insensitive and robust)
        content_lower = content.lower()
        if "label: correct" in content_lower:
            return "Correct", content
        elif "label: incorrect" in content_lower:
            return "Incorrect", content
        else:
            # Fallback: look for "Correct" or "Incorrect" at the end
            last_part = content_lower[-100:]
            if "incorrect" in last_part:
                return "Incorrect", content
            elif "correct" in last_part:
                return "Correct", content
                
            return "Unknown", content
            
    except Exception as e:
        return None, str(e)

def main():
    # Ensure output directory exists
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    
    print("Loading HelpSteer2 dataset...")
    try:
        from datasets import load_dataset
        dataset = load_dataset("nvidia/HelpSteer2", split="train")
        df = pd.DataFrame(dataset)
    except Exception as e:
        print(f"Error loading dataset: {e}")
        return

    print(f"Total rows: {len(df)}")
    
    # Filter unique prompts (take the first occurrence)
    unique_df = df.drop_duplicates(subset=["prompt"]).copy()
    print(f"Unique prompts: {len(unique_df)}")
    
    # Check for existing results to resume
    existing_prompts = set()
    if OUTPUT_FILE.exists():
        print(f"Checking existing results in {OUTPUT_FILE}...")
        with open(OUTPUT_FILE, "r") as f:
            for line in f:
                try:
                    data = json.loads(line)
                    existing_prompts.add(data["prompt"])
                except json.JSONDecodeError:
                    pass
        print(f"Found {len(existing_prompts)} existing results. Resuming...")
    
    # Filter out existing prompts
    unique_df = unique_df[~unique_df["prompt"].isin(existing_prompts)]
    print(f"Prompts remaining to process: {len(unique_df)}")
    
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=None, help="Limit number of prompts to process (default: all)")
    args = parser.parse_args()
    
    if args.limit:
        unique_df = unique_df.head(args.limit)
        print(f"Limiting to first {args.limit} prompts.")
    
    results = []
    
    if len(unique_df) == 0:
        print("No new prompts to process.")
        return

    print(f"Starting evaluation of {len(unique_df)} prompts with {MAX_WORKERS} workers...")
    print(f"Model: {MODEL_ID}")
    
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = []
        for idx, row in unique_df.iterrows():
            futures.append(executor.submit(process_row, row))
            
        for future in tqdm(as_completed(futures), total=len(futures)):
            res = future.result()
            if res:
                results.append(res)
                
                # Append to JSONL immediately
                with open(OUTPUT_FILE, "a") as f:
                    f.write(json.dumps(res) + "\n")

    # Analysis
    analyze_results(results)

def process_row(row):
    prompt = row["prompt"]
    response = row["response"]
    
    # HelpSteer2 Ground Truth
    hs_score = row["correctness"]
    hs_label = "Correct" if hs_score > HELPSTEER_THRESHOLD else "Incorrect"
    
    # Gemini Prediction
    gemini_label, explanation = get_gemini_label(prompt, response)
    
    return {
        "prompt": prompt,
        "response": response,
        "helpsteer_score": hs_score,
        "helpsteer_label": hs_label,
        "gemini_label": gemini_label,
        "gemini_explanation": explanation,
        "match": hs_label == gemini_label if gemini_label in ["Correct", "Incorrect"] else False
    }

def analyze_results(results):
    if not results:
        print("No results to analyze.")
        return
        
    df = pd.DataFrame(results)
    
    # Filter valid Gemini labels
    valid_df = df[df["gemini_label"].isin(["Correct", "Incorrect"])]
    
    print("\n" + "="*50)
    print("RESULTS SUMMARY")
    print("="*50)
    print(f"Total processed: {len(df)}")
    print(f"Valid Gemini responses: {len(valid_df)}")
    
    if len(valid_df) == 0:
        return

    match_count = valid_df["match"].sum()
    accuracy = match_count / len(valid_df)
    
    print(f"Agreement: {match_count}/{len(valid_df)} ({accuracy:.2%})")
    
    # Confusion Matrix
    print("\nConfusion Matrix:")
    print(pd.crosstab(valid_df["helpsteer_label"], valid_df["gemini_label"]))
    
    # Deviations
    print("\nSample Deviations (HelpSteer says X, Gemini says Y):")
    deviations = valid_df[~valid_df["match"]].head(5)
    for _, row in deviations.iterrows():
        print(f"\nPrompt: {row['prompt'][:100]}...")
        print(f"HelpSteer: {row['helpsteer_label']} (Score: {row['helpsteer_score']})")
        print(f"Gemini: {row['gemini_label']}")
        print(f"Explanation: {row['gemini_explanation'][:200]}...")

if __name__ == "__main__":
    main()
