import os
import json
from flask import Flask, request, jsonify
from pathlib import Path

# Import your actual Production Router
from bandit_gpt.router import BanditRouter

app = Flask(__name__)

# --- 1. Initialize Components ---
# Load the production router with your config
PROJECT_ROOT = Path(__file__).parent.parent
# models.json is at src/bandit_gpt/config/models.json
# BanditRouter.create() handles auto-loading if model_registry is None

STATE_DIR = PROJECT_ROOT / "data"
STATE_DIR.mkdir(parents=True, exist_ok=True)
STATE_PATH = STATE_DIR / "bandit_state.npz"

# Initialize router (loads models.json and any saved state)
# We use the factory method 'create' which handles defaults
router = BanditRouter.create(
    model_registry=None,  # Auto-loads from src/bandit_gpt/config/models.json
    state_path=STATE_PATH if STATE_PATH.exists() else None,
    priors="warmup"       # Load the warmup joblib if available
)

@app.route('/chat/completions', methods=['POST'])
def chat_endpoint():
    data = request.json
    
    # Extract Context (Crucial for Contextual Bandits!)
    if 'messages' in data:
        prompt = data['messages'][-1]['content']
    else:
        prompt = data.get('prompt', '')
        
    user_profile = data.get('profile', 'smart_shopper')
    
    # 1. Route (Contextual Decision)
    # Returns the model ID and a Log object containing the Request ID
    model_id, log = router.route(
        prompt=prompt,
        profile=user_profile
    )
    
    # 2. Mock Generation (Replace with actual LLM call in production)
    fake_response = f"Generated by {model_id} for profile {user_profile}"
    
    return jsonify({
        "id": "chatcmpl-" + log.request_id, # OpenAI-style ID
        "object": "chat.completion",
        "model": model_id,
        "choices": [{
            "message": {"role": "assistant", "content": fake_response},
            "finish_reason": "stop"
        }],
        # CRITICAL: Send this ID back so client can report feedback!
        "system_fingerprint": log.request_id 
    })

@app.route('/feedback', methods=['POST'])
def feedback_endpoint():
    """
    Expects: { "request_id": "...", "outcome": "success" }
    """
    data = request.json
    
    # Use the Request ID to link feedback to the specific context vector (x)
    request_id = data.get('request_id') or data.get('system_fingerprint')
    outcome_type = data.get('outcome')
    
    if not request_id:
        return jsonify({"error": "Missing request_id"}), 400
    
    # Normalize Feedback (Binary Reward)
    # 1.0 = Success (Copy/Paste), 0.0 = Failure (Regenerate)
    reward = 1.0 if outcome_type in ['success', 'copy', 'thumbs_up'] else 0.0
    
    # 3. Update Bandit State (Closes the Loop)
    router.process_feedback(request_id, reward)
    
    # Optional: Periodically save state to disk
    router.save_state(STATE_PATH)
    
    return jsonify({"status": "ack", "reward": reward})

if __name__ == '__main__':
    print("🚀 Bandit Feedback Loop running on :5005")
    app.run(debug=True, port=5005)
